/**
 * knowledge-base-search.ts
 *
 * Searches the marketing site's repair knowledge base from within the
 * admin dashboard. Guides are fetched from the marketing site's /api/guides.json
 * endpoint (static JSON generated by Astro at build time).
 *
 * Usage in admin search bar:
 *   import { searchKnowledgeBase } from '@/lib/knowledge-base-search';
 *   const results = await searchKnowledgeBase('iphone battery');
 */

export interface KnowledgeBaseGuide {
  title: string;
  slug: string;
  device: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  estimatedTime: string;
  url: string;
}

let _cachedGuides: KnowledgeBaseGuide[] | null = null;

/** Fetch all guides from the marketing site's static JSON manifest */
async function fetchGuides(): Promise<KnowledgeBaseGuide[]> {
  if (_cachedGuides) return _cachedGuides;

  const marketingBase =
    process.env.NEXT_PUBLIC_MARKETING_URL ?? 'https://techmoelectronics.lk';

  try {
    const res = await fetch(`${marketingBase}/api/guides.json`, {
      next: { revalidate: 3600 }, // re-fetch at most once per hour
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = (await res.json()) as KnowledgeBaseGuide[];
    _cachedGuides = data;
    return data;
  } catch {
    // Fallback: return an empty array so the admin UI doesn't crash
    return [];
  }
}

/**
 * Full-text search over guide titles and device names.
 *
 * @param query   User's search string (case-insensitive)
 * @param limit   Maximum number of results to return (default 5)
 */
export async function searchKnowledgeBase(
  query: string,
  limit = 5
): Promise<KnowledgeBaseGuide[]> {
  if (!query.trim()) return [];

  const guides = await fetchGuides();
  const q = query.toLowerCase().trim();
  const terms = q.split(/\s+/);

  return guides
    .filter(g => {
      const haystack = `${g.title} ${g.device}`.toLowerCase();
      return terms.every(t => haystack.includes(t));
    })
    .slice(0, limit);
}

/** Invalidate the in-memory guide cache (e.g. after a deploy) */
export function invalidateKnowledgeBaseCache(): void {
  _cachedGuides = null;
}
